### Get alle DailyLogs
GET http://localhost:7070/dailylogs

### Create DailyLog
POST http://localhost:7070/api/dailylogs/
Content-Type: application/json

{}

### Read DailyLog
GET http://localhost:7070/dailylogs/10
Accept: application/json

### Update DailyLog
PUT http://localhost:7070/dailylogs/1
Content-Type: application/json

{}

### Delete DailyLog
DELETE http://localhost:7070/dailylogs/3